version: '2'
services:
  influxdb:
    command: influxd -config /etc/influxdb/influxdb.conf
    network_mode: host
    image: influxdb:1.3
    volumes:
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf
      - /var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:5.0.3
    network_mode: host
    volumes:
      - /var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - "influxdb"
